AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31

Description: >
  Infraestructura serverless inicial de UTP Assistant.

Globals:
  Function:
    Runtime: python3.14
    Timeout: 30
    MemorySize: 256
    Architectures:
      - x86_64

Resources:
  UtpAssistantHttpApi:
    Type: AWS::Serverless::HttpApi
    Properties:
      StageName: '$default'

  UtpAssistantOrchestrator:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: utp-assistant-orchestrator
      CodeUri: ../backend/orchestrator/
      Handler: app.lambda_handler

      Environment:
        Variables:
          OPENAI_SECRET_ID: utp-assistant/openai
          HUBSPOT_FUNCTION_NAME: !Ref UtpAssistantHubSpotFunction

      Policies:
        - Statement:
            - Sid: ReadOpenAISecret
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:utp-assistant/openai-*"
        - Statement:
            - Sid: InvokeHubSpotFunction
              Effect: Allow
              Action:
                - lambda:InvokeFunction
              Resource: !GetAtt UtpAssistantHubSpotFunction.Arn

      Events:
        AssistantMessage:
          Type: HttpApi
          Properties:
            ApiId: !Ref UtpAssistantHttpApi
            Path: /assistant/message
            Method: POST

  UtpAssistantJiraFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: utp-assistant-jira
      CodeUri: ../backend/functions/jira/
      Handler: app.lambda_handler

      Environment:
        Variables:
          JIRA_SECRET_ID: utp-assistant/jira

      Policies:
        - Statement:
            - Sid: ReadJiraSecret
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:utp-assistant/jira-*"


  UtpAssistantHubSpotFunction:
    Type: AWS::Serverless::Function
    Properties:
      FunctionName: utp-assistant-hubspot
      CodeUri: ../backend/functions/hubspot/
      Handler: app.lambda_handler

      Environment:
        Variables:
          HUBSPOT_SECRET_ID: utp-assistant/hubspot

      Policies:
        - Statement:
            - Sid: ReadHubSpotSecret
              Effect: Allow
              Action:
                - secretsmanager:GetSecretValue
              Resource: !Sub "arn:${AWS::Partition}:secretsmanager:${AWS::Region}:${AWS::AccountId}:secret:utp-assistant/hubspot-*"

Outputs:

  ApiUrl:
    Description: URL del endpoint principal de UTP Assistant
    Value: !Sub "https://${UtpAssistantHttpApi}.execute-api.${AWS::Region}.${AWS::URLSuffix}/assistant/message"

  OrchestratorFunctionArn:
    Description: ARN de la Lambda Orchestrator
    Value: !GetAtt UtpAssistantOrchestrator.Arn
